"""backfill-uki-cmdline.py — seed /etc/kernel/cmdline from the live boot config."""
import subprocess
import sys
from pathlib import Path

SCRIPT = (
    Path(__file__).resolve().parents[2]
    / "packaging/shedos-system/tree/usr/lib/shedos/backfill-uki-cmdline.py"
)

LIMINE = """\
# Generated by /usr/lib/shedos/render-limine-config.sh.
timeout: 3

/ShedOS Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-zen
    kernel_cmdline: root=UUID=AAA rw quiet splash loglevel=3 nowatchdog
    module_path: boot():/initramfs-linux-zen.img
"""

PLACEHOLDER = (
    "# Per-box kernel command line, baked into the signed UKI.\n"
    "SHEDOS_PLACEHOLDER_CMDLINE\n"
)


def _run(env):
    return subprocess.run(
        [sys.executable, str(SCRIPT)], env=env, capture_output=True, text=True
    )


def _env(tmp_path, *, preset=True, limine=LIMINE):
    boot = tmp_path / "boot"
    etc = tmp_path / "etc"
    boot.mkdir()
    (etc / "kernel").mkdir(parents=True)
    (etc / "mkinitcpio.d").mkdir(parents=True)
    if limine is not None:
        (boot / "limine.conf").write_text(limine)
    if preset:
        (etc / "mkinitcpio.d" / "linux-zen.preset").write_text(
            'PRESETS=("default")\ndefault_uki="/boot/efi/EFI/Linux/shedos-linux-zen.efi"\n'
        )
    return {
        "SHEDOS_UKI_BOOT_DIR": str(boot),
        "SHEDOS_UKI_ETC_ROOT": str(etc),
        "PATH": "/usr/bin:/bin",
    }


def test_seeds_cmdline_and_fallback(tmp_path):
    env = _env(tmp_path)
    assert _run(env).returncode == 0
    cmd = (tmp_path / "etc/kernel/cmdline").read_text()
    fb = (tmp_path / "etc/kernel/cmdline-fallback").read_text()
    assert cmd.strip() == "root=UUID=AAA rw quiet splash loglevel=3 nowatchdog"
    assert "quiet" not in fb and "splash" not in fb
    assert "root=UUID=AAA" in fb


def test_lifts_over_the_shipped_placeholder(tmp_path):
    """The packaged cmdline always exists as a placeholder, so the lift has to
    treat the sentinel as unwritten — otherwise no existing box ever migrates."""
    env = _env(tmp_path)
    (tmp_path / "etc/kernel/cmdline").write_text(PLACEHOLDER)
    assert _run(env).returncode == 0
    assert (tmp_path / "etc/kernel/cmdline").read_text().strip() == \
        "root=UUID=AAA rw quiet splash loglevel=3 nowatchdog"


def test_idempotent_no_clobber(tmp_path):
    env = _env(tmp_path)
    assert _run(env).returncode == 0
    (tmp_path / "etc/kernel/cmdline").write_text("HAND-EDITED\n")
    assert _run(env).returncode == 0
    assert (tmp_path / "etc/kernel/cmdline").read_text() == "HAND-EDITED\n"


def test_noop_without_uki_preset(tmp_path):
    env = _env(tmp_path, preset=False)
    assert _run(env).returncode == 0
    assert not (tmp_path / "etc/kernel/cmdline").exists()


def test_noop_without_limine(tmp_path):
    env = _env(tmp_path, limine=None)
    assert _run(env).returncode == 0
    assert not (tmp_path / "etc/kernel/cmdline").exists()
