#!/usr/bin/env bash
# Re-emit /boot/limine.conf with one entry per installed kernel (plus a
# fallback entry per kernel) and a default timeout that makes the menu
# visible. Idempotent — running twice in a row produces a byte-identical
# output.
#
# Discovers kernels via /usr/lib/modules/*/pkgbase. Each kernel package
# writes its own pkgbase file when installed (mkinitcpio convention);
# the renderer reads them all to build the entry list.
#
# Cmdline resolution, in order:
#   1. SHEDOS_LIMINE_CMDLINE env — used by the installer at fresh-install
#      time, when /boot/limine.conf doesn't exist yet
#   2. First kernel_cmdline: line in the existing /boot/limine.conf —
#      preserves anything the [kernel.cmdline] reconciler in apply_core
#      manages, plus any user hand-edits
#   3. Fail with a non-zero exit if neither is available
#
# Default boot priority (first wins):
#   1. /var/lib/shedos/kernel-default contents (if the file exists and
#      names an installed kernel) — `shedman kernel --set-default` writes
#      it
#   2. shedos-kernel (if installed)
#   3. linux
#   4. Anything else, alphabetical

set -uo pipefail

BOOT_DIR=${SHEDOS_BOOT_DIR:-/boot}
MODULES_DIR=${SHEDOS_MODULES_DIR:-/usr/lib/modules}
LIMINE_CONF=$BOOT_DIR/limine.conf
DEFAULT_FILE=${SHEDOS_KERNEL_DEFAULT_FILE:-/var/lib/shedos/kernel-default}
TIMEOUT=${SHEDOS_LIMINE_TIMEOUT:-3}

# Discover installed kernel pkgbases.
mapfile -t pkgbases < <(
    for f in "$MODULES_DIR"/*/pkgbase; do
        [[ -r $f ]] && cat "$f"
    done | sort -u
)

if (( ${#pkgbases[@]} == 0 )); then
    echo "render-limine-config: no kernels found under $MODULES_DIR/*/pkgbase" >&2
    exit 1
fi

# Build the boot order. User-chosen default first, then shedos-kernel,
# then linux, then everything else alphabetical. Each pkgbase appears
# exactly once.
user_default=""
[[ -r $DEFAULT_FILE ]] && user_default=$(<"$DEFAULT_FILE")

declare -A added=()
ordered=()

_add() {
    local k=$1
    [[ -n ${added[$k]:-} ]] && return
    added[$k]=1
    ordered+=("$k")
}

_have_pkgbase() {
    local needle=$1 k
    for k in "${pkgbases[@]}"; do
        [[ $k == "$needle" ]] && return 0
    done
    return 1
}

if [[ -n $user_default ]] && _have_pkgbase "$user_default"; then
    _add "$user_default"
fi
_have_pkgbase shedos-kernel && _add shedos-kernel
_have_pkgbase linux && _add linux
for k in "${pkgbases[@]}"; do
    _add "$k"
done

# Resolve cmdline.
cmdline=${SHEDOS_LIMINE_CMDLINE:-}
if [[ -z $cmdline && -f $LIMINE_CONF ]]; then
    cmdline=$(awk '
        /^[[:space:]]*kernel_cmdline:/ {
            sub(/^[[:space:]]*kernel_cmdline:[[:space:]]*/, "", $0)
            print
            exit
        }' "$LIMINE_CONF")
fi
if [[ -z $cmdline ]]; then
    echo "render-limine-config: no cmdline available — set SHEDOS_LIMINE_CMDLINE or seed $LIMINE_CONF first" >&2
    exit 1
fi

# Fallback entries strip quiet/splash so the boot log is visible.
# Use word-boundary matches so removing `quiet` doesn't consume the
# trailing space `splash` would otherwise match against.
cmdline_fallback=$(printf '%s\n' "$cmdline" \
    | sed -E 's/\<(quiet|splash)\>//g; s/[[:space:]]+/ /g; s/^ //; s/ $//')

_display_name() {
    case "$1" in
        shedos-kernel) echo "ShedOS Linux" ;;
        linux)         echo "ShedOS Linux (stock)" ;;
        *)             echo "ShedOS Linux ($1)" ;;
    esac
}

tmp=$(mktemp)
trap 'rm -f -- "$tmp"' EXIT

{
    echo "# Generated by /usr/lib/shedos/render-limine-config.sh."
    echo "# Edits to kernel_cmdline survive regeneration; entries are"
    echo "# rewritten on every kernel install/upgrade. To change the"
    echo "# default entry: sudo shedman kernel --set-default <pkgbase>"
    echo "timeout: $TIMEOUT"
    echo
    for k in "${ordered[@]}"; do
        name=$(_display_name "$k")
        cat <<EOF
/$name
    protocol: linux
    kernel_path: boot():/vmlinuz-$k
    kernel_cmdline: $cmdline
    module_path: boot():/initramfs-$k.img

/$name (Fallback)
    protocol: linux
    kernel_path: boot():/vmlinuz-$k
    kernel_cmdline: $cmdline_fallback
    module_path: boot():/initramfs-$k-fallback.img

EOF
    done
} > "$tmp"

install -Dm644 "$tmp" "$LIMINE_CONF"
echo "render-limine-config: wrote $LIMINE_CONF (${#ordered[@]} kernel(s), timeout=$TIMEOUT, default=${ordered[0]})"
