#!/usr/bin/env bash
# Re-emit /boot/limine.conf with one entry per installed kernel (plus a
# fallback entry per kernel) and a default timeout that makes the menu
# visible. Idempotent; running twice in a row produces a byte-identical
# output.
#
# Discovers kernels via /usr/lib/modules/*/pkgbase. Each kernel package
# writes its own pkgbase file when installed (mkinitcpio convention);
# the renderer reads them all to build the entry list.
#
# Cmdline resolution, in order:
#   1. SHEDOS_LIMINE_CMDLINE env; used by the installer at fresh-install
#      time, when /boot/limine.conf doesn't exist yet
#   2. First kernel_cmdline: line in the existing /boot/limine.conf —
#      preserves anything the [kernel.cmdline] reconciler in apply_core
#      manages, plus any user hand-edits
#   3. Fail with a non-zero exit if neither is available
#
# Default boot priority (first wins):
#   1. /var/lib/shedos/kernel-default contents (if the file exists and
#      names an installed kernel); `shedman kernel --set-default` writes
#      it
#   2. linux-zen (if installed)
#   3. linux
#   4. Anything else, alphabetical

set -uo pipefail

BOOT_DIR=${SHEDOS_BOOT_DIR:-/boot}
MODULES_DIR=${SHEDOS_MODULES_DIR:-/usr/lib/modules}
LIMINE_CONF=$BOOT_DIR/limine.conf
DEFAULT_FILE=${SHEDOS_KERNEL_DEFAULT_FILE:-/var/lib/shedos/kernel-default}
TIMEOUT=${SHEDOS_LIMINE_TIMEOUT:-3}

# Discover installed kernel pkgbases.
mapfile -t pkgbases < <(
    for f in "$MODULES_DIR"/*/pkgbase; do
        [[ -r $f ]] && cat "$f"
    done | sort -u
)

if (( ${#pkgbases[@]} == 0 )); then
    echo "render-limine-config: no kernels found under $MODULES_DIR/*/pkgbase" >&2
    exit 1
fi

# Build the boot order. User-chosen default first, then linux-zen,
# then linux, then everything else alphabetical. Each pkgbase appears
# exactly once.
user_default=""
[[ -r $DEFAULT_FILE ]] && user_default=$(<"$DEFAULT_FILE")

declare -A added=()
ordered=()

_add() {
    local k=$1
    [[ -n ${added[$k]:-} ]] && return
    added[$k]=1
    ordered+=("$k")
}

_have_pkgbase() {
    local needle=$1 k
    for k in "${pkgbases[@]}"; do
        [[ $k == "$needle" ]] && return 0
    done
    return 1
}

if [[ -n $user_default ]] && _have_pkgbase "$user_default"; then
    _add "$user_default"
fi
_have_pkgbase linux-zen && _add linux-zen
_have_pkgbase linux && _add linux
for k in "${pkgbases[@]}"; do
    _add "$k"
done

# Resolve cmdline.
cmdline=${SHEDOS_LIMINE_CMDLINE:-}
if [[ -z $cmdline && -f $LIMINE_CONF ]]; then
    cmdline=$(awk '
        /^[[:space:]]*kernel_cmdline:/ {
            sub(/^[[:space:]]*kernel_cmdline:[[:space:]]*/, "", $0)
            print
            exit
        }' "$LIMINE_CONF")
fi
if [[ -z $cmdline ]]; then
    echo "render-limine-config: no cmdline available — set SHEDOS_LIMINE_CMDLINE or seed $LIMINE_CONF first" >&2
    exit 1
fi

# Fallback entries strip quiet/splash so the boot log is visible.
# Use word-boundary matches so removing `quiet` doesn't consume the
# trailing space `splash` would otherwise match against.
cmdline_fallback=$(printf '%s\n' "$cmdline" \
    | sed -E 's/\<(quiet|splash)\>//g; s/[[:space:]]+/ /g; s/^ //; s/ $//')

_display_name() {
    case "$1" in
        linux-zen)     echo "ShedOS Linux" ;;
        linux)         echo "ShedOS Linux (stock)" ;;
        *)             echo "ShedOS Linux ($1)" ;;
    esac
}

tmp=$(mktemp)
trap 'rm -f -- "$tmp"' EXIT

{
    echo "# Generated by /usr/lib/shedos/render-limine-config.sh."
    echo "# Edits to kernel_cmdline survive regeneration; entries are"
    echo "# rewritten on every kernel install/upgrade. To change the"
    echo "# default entry: sudo shedman kernel --set-default <pkgbase>"
    echo "timeout: $TIMEOUT"
    echo
    for k in "${ordered[@]}"; do
        name=$(_display_name "$k")
        cat <<EOF
/$name
    protocol: linux
    kernel_path: boot():/vmlinuz-$k
    kernel_cmdline: $cmdline
    module_path: boot():/initramfs-$k.img

EOF
        # Only emit the recovery entry when the fallback initramfs exists.
        # mkinitcpio's stock preset template is default-only, so a kernel
        # without a shipped both-presets file (e.g. the stock linux
        # fallback) has no initramfs-$k-fallback.img — emitting the entry
        # anyway would dead-end the boot.
        if [[ -f $BOOT_DIR/initramfs-$k-fallback.img ]]; then
            cat <<EOF
/$name (Fallback)
    protocol: linux
    kernel_path: boot():/vmlinuz-$k
    kernel_cmdline: $cmdline_fallback
    module_path: boot():/initramfs-$k-fallback.img

EOF
        fi
    done

    # Verbatim extra entries (e.g. the Windows chainload the installer
    # writes on dual-boot machines). Appended on every render so they
    # survive the wholesale rewrite above.
    extra=/etc/shedos/limine-extra-entries.conf
    if [[ -f $extra ]]; then
        echo
        cat "$extra"
    fi
} > "$tmp"

install -Dm644 "$tmp" "$LIMINE_CONF"
echo "render-limine-config: wrote $LIMINE_CONF (${#ordered[@]} kernel(s), timeout=$TIMEOUT, default=${ordered[0]})"

# Mirror the freshly-rendered config into every existing ESP path.
# Limine boots from the ESP, not from /boot/limine.conf, so any change
# to the seed file must propagate or the firmware will load stale
# entries (kernel cmdline drift, missing/extra kernel entries, etc.).
# Mirror set matches apply_core._ESP_LIMINE_MIRRORS so the two writers
# of /boot/limine.conf (apply_core's cmdline reconciler + this script)
# stay in lockstep. install -Dm644 is idempotent; only existing ESP
# files are touched (we don't create a new ESP layout).
for esp in \
    /boot/efi/EFI/limine/limine.conf \
    /boot/efi/limine.conf \
    /efi/EFI/limine/limine.conf \
    /efi/limine.conf
do
    if [[ -f $esp ]]; then
        install -Dm644 "$tmp" "$esp" 2>/dev/null \
            && echo "render-limine-config: mirrored to $esp"
    fi
done

# Limine boots the KERNELS from that FAT volume too (its own drivers
# read only FAT/ISO9660 — /boot on btrfs is invisible to it), so the
# freshly built vmlinuz/initramfs must follow the config. Without this
# the ESP kept the install-day images forever: the first kernel
# upgrade would boot the old kernel against the new modules tree.
for esp_dir in /boot/efi /efi; do
    [[ -f $esp_dir/limine.conf || -f $esp_dir/EFI/limine/limine.conf ]] \
        || continue
    for k in "${ordered[@]}"; do
        for f in "vmlinuz-$k" "initramfs-$k.img" \
                 "initramfs-$k-fallback.img"; do
            src=$BOOT_DIR/$f
            [[ -f $src ]] || continue
            if ! cmp -s -- "$src" "$esp_dir/$f"; then
                install -Dm600 "$src" "$esp_dir/$f" 2>/dev/null \
                    && echo "render-limine-config: synced $f to $esp_dir"
            fi
        done
    done
done
